server:
  port: 8082

spring:
  application:
    name: cadastro-usuarios
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:postgresql://localhost:5432/usuarios
    username: root
    password: root
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

jwt:
  refresh:
    expiration:
      days: 1
  expiration:
    seconds: 3600
  public:
    key: classpath:keys/public.pem
  private:
    key: classpath:keys/private.pem

logging:
  pattern:
    console: '%clr(%d{HH:mm:ss}){faint} %clr(%5p) %clr(%-30.30logger{25}){cyan} %clr(:){yellow} %m%n'
  level:
    root: INFO
    io.github.nivaldosilva: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.flywaydb: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE